name: samples
description: creomobile samples app

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  combos_example:
    git:
      url: https://github.com/creomobile/combos
      path: example/
  calendart_example:
    git:
      url: https://github.com/creomobile/calendart
      path: example/

dev_dependencies:

flutter:
  uses-material-design: true
